# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, 15.5
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'FaceRN' do
  pod 'FaceAISDK_Core', :git => 'https://github.com/FaceAISDK/FaceAISDK_Core.git', :tag => '2026.05.21.xcode265'
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  post_install do |installer|
      react_native_post_install(
        installer,
        config[:reactNativePath],
        :mac_catalyst_enabled => false,
        # :ccache_enabled => true
      )
      
      # 1. 优化全局项目配置
      installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"  ## 兼容模拟器
        config.build_settings["CLANG_ENABLE_MODULES"] = "YES"
      end
      
      # 2. 遍历所有 target 并修复 RCTSwiftUI 错误 (修复语法错误的关键)
      installer.pods_project.targets.each do |target|
        if target.name == 'RCTSwiftUI'
          target.build_configurations.each do |config|
            # 强制允许 Swift 模块共享其头文件映射，解决 no such module 'React'
            config.build_settings['DEFINES_MODULE'] = 'YES'
          end
        end
      end
    
  end
end

